 -- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.caixa (
  id integer NOT NULL DEFAULT nextval('caixa_id_seq'::regclass),
  loja_id integer NOT NULL,
  usuario_id uuid,
  data_abertura timestamp with time zone NOT NULL DEFAULT now(),
  valor_inicial numeric NOT NULL DEFAULT 0,
  status character varying NOT NULL DEFAULT 'aberto'::character varying CHECK (status::text = ANY (ARRAY['aberto'::character varying, 'fechado'::character varying]::text[])),
  data_fechamento timestamp with time zone,
  valor_final numeric,
  observacoes_abertura text,
  observacoes_fechamento text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT caixa_pkey PRIMARY KEY (id),
  CONSTRAINT caixa_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES public.lojas(id),
  CONSTRAINT caixa_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(uuid)
);
CREATE TABLE public.caixa_aparelhos (
  id integer NOT NULL DEFAULT nextval('caixa_aparelhos_id_seq'::regclass),
  loja_id integer NOT NULL,
  usuario_id uuid NOT NULL,
  data_abertura timestamp with time zone NOT NULL DEFAULT now(),
  valor_inicial numeric NOT NULL DEFAULT 0,
  status character varying NOT NULL DEFAULT 'aberto'::character varying CHECK (status::text = ANY (ARRAY['aberto'::character varying, 'fechado'::character varying]::text[])),
  data_fechamento timestamp with time zone,
  valor_final numeric,
  observacoes_abertura text,
  observacoes_fechamento text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT caixa_aparelhos_pkey PRIMARY KEY (id),
  CONSTRAINT caixa_aparelhos_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES public.lojas(id),
  CONSTRAINT caixa_aparelhos_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(uuid)
);
CREATE TABLE public.caixa_aparelhos_movimentacoes (
  id integer NOT NULL DEFAULT nextval('caixa_aparelhos_movimentacoes_id_seq'::regclass),
  caixa_id integer NOT NULL,
  venda_aparelho_uuid uuid,
  tipo character varying NOT NULL CHECK (tipo::text = ANY (ARRAY['venda'::character varying, 'entrada'::character varying, 'saida'::character varying, 'sangria'::character varying, 'reforco'::character varying]::text[])),
  valor numeric NOT NULL,
  forma_pagamento text,
  descricao text,
  usuario_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT caixa_aparelhos_movimentacoes_pkey PRIMARY KEY (id),
  CONSTRAINT caixa_aparelhos_movimentacoes_caixa_id_fkey FOREIGN KEY (caixa_id) REFERENCES public.caixa_aparelhos(id),
  CONSTRAINT caixa_aparelhos_movimentacoes_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(uuid),
  CONSTRAINT caixa_aparelhos_movimentacoes_venda_aparelho_uuid_fkey FOREIGN KEY (venda_aparelho_uuid) REFERENCES public.vendas_aparelhos(uuid)
);
CREATE TABLE public.clientes (
  nome text,
  email text,
  telefone text,
  doc text UNIQUE,
  endereco text,
  instagram text,
  whatsapp boolean,
  createdat timestamp without time zone DEFAULT now(),
  updatedat timestamp without time zone DEFAULT now(),
  fotourl ARRAY,
  id integer NOT NULL DEFAULT nextval('clientes_id_seq'::regclass),
  credito numeric,
  updated_at timestamp without time zone DEFAULT now(),
  usuario_id uuid,
  CONSTRAINT clientes_pkey PRIMARY KEY (id),
  CONSTRAINT clientes_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(uuid)
);
CREATE TABLE public.clientes_creditos (
  id bigint NOT NULL DEFAULT nextval('clientes_creditos_id_seq'::regclass),
  cliente_id bigint NOT NULL,
  tipo text NOT NULL CHECK (tipo = ANY (ARRAY['add'::text, 'remove'::text])),
  valor numeric NOT NULL DEFAULT 0,
  observacao text,
  saldo_apos numeric,
  createdat timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT clientes_creditos_pkey PRIMARY KEY (id),
  CONSTRAINT clientes_creditos_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id),
  CONSTRAINT fk_clientes_creditos_created_by FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.devolucoes (
  id bigint NOT NULL DEFAULT nextval('devolucoes_id_seq'::regclass),
  id_venda bigint NOT NULL,
  data_devolucao timestamp without time zone DEFAULT now(),
  id_cliente integer,
  cliente_nome text,
  usuario_id uuid,
  itens_devolvidos jsonb DEFAULT '[]'::jsonb,
  valor_total_devolvido numeric DEFAULT 0,
  tipo_devolucao text CHECK (tipo_devolucao = ANY (ARRAY['total'::text, 'parcial'::text])),
  motivo_devolucao text,
  valor_credito_gerado numeric DEFAULT 0,
  credito_aplicado boolean DEFAULT false,
  observacoes text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  id_usuario uuid,
  status text DEFAULT 'pendente'::text CHECK (status = ANY (ARRAY['pendente'::text, 'concluida'::text, 'concluida_com_credito'::text])),
  forma_reembolso text NOT NULL DEFAULT 'credito'::text,
  CONSTRAINT devolucoes_pkey PRIMARY KEY (id),
  CONSTRAINT devolucoes_id_usuario_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(uuid),
  CONSTRAINT fk_devolucoes_usuario FOREIGN KEY (id_usuario) REFERENCES auth.users(id),
  CONSTRAINT devolucoes_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(uuid)
);
CREATE TABLE public.estoque (
  id integer NOT NULL DEFAULT nextval('estoque_id_seq'::regclass),
  descricao text,
  modelo text,
  marca text,
  compativel text,
  minimo numeric,
  preco_compra numeric,
  preco_venda numeric,
  createdat timestamp without time zone DEFAULT now(),
  updatedat timestamp without time zone DEFAULT now(),
  fotourl ARRAY,
  observacoes text,
  usuario_id uuid,
  CONSTRAINT estoque_pkey PRIMARY KEY (id),
  CONSTRAINT estoque_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(uuid)
);
CREATE TABLE public.estoque_alertas (
  id bigint NOT NULL DEFAULT nextval('estoque_alertas_id_seq'::regclass),
  produto_id integer NOT NULL,
  loja_id integer,
  status text NOT NULL DEFAULT 'aberto'::text,
  sent_at timestamp with time zone NOT NULL DEFAULT now(),
  closed_at timestamp with time zone,
  last_quantidade integer NOT NULL DEFAULT 0,
  minimo integer NOT NULL DEFAULT 0,
  CONSTRAINT estoque_alertas_pkey PRIMARY KEY (id),
  CONSTRAINT estoque_alertas_produto_id_fkey FOREIGN KEY (produto_id) REFERENCES public.estoque(id),
  CONSTRAINT estoque_alertas_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES public.lojas(id)
);
CREATE TABLE public.estoque_aparelhos (
  id integer NOT NULL DEFAULT nextval('estoque_aparelhos_id_seq'::regclass),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  marca text NOT NULL,
  modelo text NOT NULL,
  imei text UNIQUE,
  serial text,
  cor text,
  capacidade text,
  estado text CHECK (estado = ANY (ARRAY['novo'::text, 'seminovo'::text, 'usado'::text])),
  bateria integer CHECK (bateria >= 0 AND bateria <= 100),
  bloqueado boolean DEFAULT false,
  bloqueio_tipo text,
  defeitos ARRAY,
  acessorios ARRAY,
  preco_compra numeric,
  preco_venda numeric NOT NULL CHECK (preco_venda >= 0::numeric),
  custo_reparo numeric DEFAULT 0,
  status text DEFAULT 'disponivel'::text CHECK (status = ANY (ARRAY['disponivel'::text, 'reservado'::text, 'vendido'::text, 'em_reparo'::text, 'defeito'::text])),
  loja_id integer,
  fornecedor_id integer,
  data_entrada date DEFAULT CURRENT_DATE,
  nota_fiscal text,
  garantia_fornecedor_meses integer,
  garantia_fornecedor_expira_em date,
  fotos ARRAY,
  checklist_entrada jsonb,
  observacoes text,
  usuario_cadastro_id uuid,
  venda_id uuid,
  tags ARRAY,
  metadata jsonb,
  CONSTRAINT estoque_aparelhos_pkey PRIMARY KEY (id),
  CONSTRAINT estoque_aparelhos_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES public.lojas(id),
  CONSTRAINT estoque_aparelhos_fornecedor_id_fkey FOREIGN KEY (fornecedor_id) REFERENCES public.fornecedores(id),
  CONSTRAINT estoque_aparelhos_usuario_cadastro_id_fkey FOREIGN KEY (usuario_cadastro_id) REFERENCES public.usuarios(uuid),
  CONSTRAINT estoque_aparelhos_venda_id_fkey FOREIGN KEY (venda_id) REFERENCES public.vendas_aparelhos(uuid)
);
CREATE TABLE public.estoque_aparelhos_historico (
  id integer NOT NULL DEFAULT nextval('estoque_aparelhos_historico_id_seq'::regclass),
  aparelho_id integer NOT NULL,
  tipo_evento text NOT NULL CHECK (tipo_evento = ANY (ARRAY['entrada'::text, 'venda'::text, 'reparo'::text, 'transferencia'::text, 'reserva'::text, 'cancelamento'::text, 'devolucao'::text])),
  descricao text,
  valor numeric,
  usuario_id uuid,
  loja_origem_id integer,
  loja_destino_id integer,
  dados_evento jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT estoque_aparelhos_historico_pkey PRIMARY KEY (id),
  CONSTRAINT estoque_aparelhos_historico_aparelho_id_fkey FOREIGN KEY (aparelho_id) REFERENCES public.estoque_aparelhos(id),
  CONSTRAINT estoque_aparelhos_historico_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(uuid),
  CONSTRAINT estoque_aparelhos_historico_loja_origem_id_fkey FOREIGN KEY (loja_origem_id) REFERENCES public.lojas(id),
  CONSTRAINT estoque_aparelhos_historico_loja_destino_id_fkey FOREIGN KEY (loja_destino_id) REFERENCES public.lojas(id)
);
CREATE TABLE public.estoque_historico (
  id bigint NOT NULL DEFAULT nextval('estoque_historico_id_seq'::regclass),
  produto_id bigint NOT NULL,
  loja_id bigint NOT NULL,
  quantidade_anterior integer NOT NULL DEFAULT 0,
  quantidade_nova integer NOT NULL DEFAULT 0,
  quantidade_alterada integer NOT NULL,
  tipo_operacao character varying,
  usuario_id uuid,
  usuario_nome character varying,
  observacao text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT estoque_historico_pkey PRIMARY KEY (id),
  CONSTRAINT fk_produto FOREIGN KEY (produto_id) REFERENCES public.estoque(id),
  CONSTRAINT fk_loja FOREIGN KEY (loja_id) REFERENCES public.lojas(id),
  CONSTRAINT fk_usuario FOREIGN KEY (usuario_id) REFERENCES auth.users(id)
);
CREATE TABLE public.estoque_lojas (
  id integer NOT NULL DEFAULT nextval('estoque_lojas_id_seq'::regclass),
  produto_id integer,
  loja_id integer,
  quantidade numeric DEFAULT 0,
  updatedat timestamp without time zone DEFAULT now(),
  usuario_id uuid,
  CONSTRAINT estoque_lojas_pkey PRIMARY KEY (id),
  CONSTRAINT estoque_lojas_produto_id_fkey FOREIGN KEY (produto_id) REFERENCES public.estoque(id),
  CONSTRAINT estoque_lojas_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES public.lojas(id),
  CONSTRAINT estoque_lojas_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(uuid)
);
CREATE TABLE public.fornecedores (
  id integer NOT NULL DEFAULT nextval('clientes_id_seq'::regclass),
  nome character varying NOT NULL,
  doc character varying UNIQUE,
  email character varying,
  telefone character varying,
  cep character varying,
  endereco text,
  site character varying,
  produtos jsonb,
  ativo boolean DEFAULT true,
  data_cadastro timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  observacoes text,
  fotourl ARRAY,
  usuario_id uuid,
  CONSTRAINT fornecedores_pkey PRIMARY KEY (id),
  CONSTRAINT fornecedores_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(uuid)
);
CREATE TABLE public.logs (
  id bigint NOT NULL DEFAULT nextval('logs_id_seq'::regclass),
  usuario_id uuid,
  acao text NOT NULL,
  tabela text,
  registro_id text,
  dados_anteriores jsonb,
  dados_novos jsonb,
  ip text,
  user_agent text,
  criado_em timestamp with time zone DEFAULT now(),
  tipo_operacao character varying,
  descricao text,
  modulo character varying,
  CONSTRAINT logs_pkey PRIMARY KEY (id),
  CONSTRAINT logs_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(uuid)
);
CREATE TABLE public.lojas (
  id integer NOT NULL DEFAULT nextval('lojas_id_seq'::regclass),
  nome text NOT NULL,
  endereco text,
  telefone text,
  createdat timestamp without time zone DEFAULT now(),
  updatedat timestamp without time zone DEFAULT now(),
  fotourl ARRAY,
  descricao text,
  usuario_id uuid,
  CONSTRAINT lojas_pkey PRIMARY KEY (id),
  CONSTRAINT lojas_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(uuid)
);
CREATE TABLE public.ordens (
  id integer NOT NULL DEFAULT nextval('ordens_id_seq'::regclass),
  modelo text,
  cor text,
  defeito text,
  diagnostico text,
  entrada date,
  saida date,
  forma_pagamento text,
  status text,
  garantia boolean,
  periodo_garantia text,
  observacoes text,
  prazo date,
  prioridade text,
  tecnico_responsavel text,
  valor numeric,
  id_cliente integer,
  createdat timestamp without time zone DEFAULT now(),
  updatedat timestamp without time zone DEFAULT now(),
  fotourl ARRAY,
  usuario_id uuid,
  CONSTRAINT ordens_pkey PRIMARY KEY (id),
  CONSTRAINT ordens_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(uuid)
);
CREATE TABLE public.permissoes (
  id uuid NOT NULL,
  acessos jsonb NOT NULL,
  loja_id integer,
  CONSTRAINT permissoes_pkey PRIMARY KEY (id),
  CONSTRAINT fk_permissoes_loja FOREIGN KEY (loja_id) REFERENCES public.lojas(id)
);
CREATE TABLE public.rma (
  id integer NOT NULL DEFAULT nextval('rma_id_seq'::regclass),
  produto_id integer NOT NULL,
  loja_id integer,
  quantidade integer NOT NULL DEFAULT 1,
  motivo text,
  tipo_rma text CHECK (tipo_rma = ANY (ARRAY['troca'::text, 'garantia'::text, 'assistencia'::text])),
  data_rma timestamp without time zone DEFAULT now(),
  status text DEFAULT 'pendente'::text,
  enviado_assistencia boolean DEFAULT false,
  data_envio timestamp without time zone,
  data_retorno timestamp without time zone,
  observacoes text,
  usuario_id uuid,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  fotourl ARRAY,
  cliente_id integer,
  tipo_rma_origem character varying DEFAULT 'interno'::character varying,
  numero_rma character varying,
  codigo_rastreio character varying,
  analise_interna text,
  inspecao text,
  solucao text,
  CONSTRAINT rma_pkey PRIMARY KEY (id),
  CONSTRAINT rma_produto_id_fkey FOREIGN KEY (produto_id) REFERENCES public.estoque(id),
  CONSTRAINT rma_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES public.lojas(id),
  CONSTRAINT rma_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id),
  CONSTRAINT rma_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(uuid)
);
CREATE TABLE public.rma_clientes (
  id integer NOT NULL DEFAULT nextval('rma_clientes_id_seq'::regclass),
  produto_id integer,
  cliente_id integer,
  loja_id integer,
  usuario_id uuid,
  quantidade integer DEFAULT 1,
  motivo text,
  tipo_rma character varying,
  status character varying DEFAULT 'solicitado'::character varying,
  numero_rma character varying,
  codigo_rastreio character varying,
  observacoes text,
  analise_interna text,
  inspecao text,
  solucao text,
  fotourl ARRAY,
  data_rma timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT rma_clientes_pkey PRIMARY KEY (id),
  CONSTRAINT rma_clientes_produto_id_fkey FOREIGN KEY (produto_id) REFERENCES public.estoque(id),
  CONSTRAINT rma_clientes_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id),
  CONSTRAINT rma_clientes_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES public.lojas(id),
  CONSTRAINT rma_clientes_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(uuid)
);
CREATE TABLE public.sangrias (
  id integer NOT NULL DEFAULT nextval('sangrias_id_seq'::regclass),
  caixa_id integer NOT NULL,
  valor numeric NOT NULL CHECK (valor > 0::numeric),
  motivo text NOT NULL CHECK (length(TRIM(BOTH FROM motivo)) > 0),
  data_sangria timestamp with time zone NOT NULL,
  usuario_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  status character varying DEFAULT 'ativa'::character varying CHECK (status::text = ANY (ARRAY['ativa'::character varying, 'cancelada'::character varying]::text[])),
  motivo_cancelamento text,
  data_cancelamento timestamp with time zone,
  usuario_cancelamento_id uuid,
  CONSTRAINT sangrias_pkey PRIMARY KEY (id),
  CONSTRAINT fk_sangrias_caixa FOREIGN KEY (caixa_id) REFERENCES public.caixa(id),
  CONSTRAINT fk_sangrias_usuario FOREIGN KEY (usuario_id) REFERENCES auth.users(id),
  CONSTRAINT sangrias_usuario_cancelamento_id_fkey FOREIGN KEY (usuario_cancelamento_id) REFERENCES auth.users(id)
);
CREATE TABLE public.transferencia_itens (
  id integer NOT NULL DEFAULT nextval('transferencia_itens_id_seq'::regclass),
  transferencia_id integer NOT NULL,
  produto_id integer NOT NULL,
  quantidade integer NOT NULL,
  createdat timestamp without time zone DEFAULT now(),
  usuario_id uuid,
  CONSTRAINT transferencia_itens_pkey PRIMARY KEY (id),
  CONSTRAINT transferencia_itens_transferencia_id_fkey FOREIGN KEY (transferencia_id) REFERENCES public.transferencias(id),
  CONSTRAINT transferencia_itens_produto_id_fkey FOREIGN KEY (produto_id) REFERENCES public.estoque(id),
  CONSTRAINT transferencia_itens_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(uuid)
);
CREATE TABLE public.transferencias (
  id integer NOT NULL DEFAULT nextval('transferencias_id_seq'::regclass),
  loja_origem_id integer NOT NULL,
  loja_destino_id integer NOT NULL,
  usuario_id uuid,
  data_transferencia timestamp without time zone DEFAULT now(),
  observacoes text,
  status character varying DEFAULT 'pendente'::character varying,
  createdat timestamp without time zone DEFAULT now(),
  updatedat timestamp without time zone DEFAULT now(),
  CONSTRAINT transferencias_pkey PRIMARY KEY (id),
  CONSTRAINT transferencias_loja_origem_id_fkey FOREIGN KEY (loja_origem_id) REFERENCES public.lojas(id),
  CONSTRAINT transferencias_loja_destino_id_fkey FOREIGN KEY (loja_destino_id) REFERENCES public.lojas(id),
  CONSTRAINT transferencias_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(uuid)
);
CREATE TABLE public.usuarios (
  uuid uuid NOT NULL DEFAULT gen_random_uuid(),
  nome text,
  nickname text,
  email text UNIQUE,
  telefone text,
  cpf text UNIQUE,
  cargo text,
  fotourl ARRAY,
  createdat timestamp without time zone DEFAULT now(),
  updatedat timestamp without time zone DEFAULT now(),
  credito numeric,
  CONSTRAINT usuarios_pkey PRIMARY KEY (uuid)
);
CREATE TABLE public.vendas (
  id bigint NOT NULL DEFAULT nextval('vendas_id_seq'::regclass),
  data_venda timestamp with time zone DEFAULT now(),
  id_cliente integer,
  cliente_nome text,
  usuario_id uuid,
  itens jsonb DEFAULT '[]'::jsonb,
  total_bruto numeric DEFAULT 0,
  desconto numeric DEFAULT 0,
  total_liquido numeric DEFAULT 0,
  forma_pagamento text,
  status_pagamento text DEFAULT 'pendente'::text,
  fiado boolean DEFAULT false,
  data_vencimento date,
  valor_pago numeric DEFAULT 0,
  valor_restante numeric DEFAULT 0,
  observacoes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  loja_id integer,
  credito_usado numeric DEFAULT 0,
  id_usuario uuid,
  comprovantes ARRAY,
  data_pagamento timestamp with time zone,
  credito_gerado_por_devolucao boolean DEFAULT false,
  pagamento_detalhes jsonb,
  CONSTRAINT vendas_pkey PRIMARY KEY (id),
  CONSTRAINT vendas_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES public.lojas(id),
  CONSTRAINT vendas_id_usuario_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(uuid),
  CONSTRAINT vendas_id_usuario_fkey1 FOREIGN KEY (id_usuario) REFERENCES public.usuarios(uuid),
  CONSTRAINT vendas_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(uuid)
);
CREATE TABLE public.vendas_aparelhos (
  uuid uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  cliente_id integer,
  cliente_nome text NOT NULL,
  cliente_cpf text,
  cliente_telefone text,
  cliente_email text,
  aparelho_marca text NOT NULL,
  aparelho_modelo text NOT NULL,
  aparelho_imei text UNIQUE,
  aparelho_serial text,
  aparelho_cor text,
  aparelho_capacidade text,
  aparelho_estado text CHECK (aparelho_estado = ANY (ARRAY['novo'::text, 'seminovo'::text, 'usado'::text])),
  aparelho_bateria integer CHECK (aparelho_bateria >= 0 AND aparelho_bateria <= 100),
  aparelho_defeitos ARRAY,
  aparelho_acessorios ARRAY,
  aparelho_observacoes text,
  aparelho_fotos ARRAY,
  valor_aparelho numeric NOT NULL CHECK (valor_aparelho >= 0::numeric),
  desconto numeric DEFAULT 0 CHECK (desconto >= 0::numeric),
  valor_final numeric NOT NULL CHECK (valor_final >= 0::numeric),
  forma_pagamento text NOT NULL CHECK (forma_pagamento = ANY (ARRAY['dinheiro'::text, 'pix'::text, 'debito'::text, 'credito'::text, 'carteira_digital'::text, 'misto'::text])),
  pagamento_detalhes jsonb,
  parcelas integer DEFAULT 1,
  status text DEFAULT 'pendente'::text CHECK (status = ANY (ARRAY['pendente'::text, 'pago'::text, 'cancelado'::text, 'estornado'::text])),
  loja_id integer,
  vendedor_id uuid,
  garantia_meses integer DEFAULT 3,
  garantia_expira_em date,
  nota_fiscal text,
  termo_venda_url text,
  checklist_fotos ARRAY,
  tags ARRAY,
  metadata jsonb,
  estoque_aparelho_id integer,
  CONSTRAINT vendas_aparelhos_pkey PRIMARY KEY (uuid),
  CONSTRAINT vendas_aparelhos_vendedor_id_fkey FOREIGN KEY (vendedor_id) REFERENCES public.usuarios(uuid),
  CONSTRAINT vendas_aparelhos_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id),
  CONSTRAINT vendas_aparelhos_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES public.lojas(id),
  CONSTRAINT vendas_aparelhos_estoque_aparelho_id_fkey FOREIGN KEY (estoque_aparelho_id) REFERENCES public.estoque_aparelhos(id)
);
CREATE TABLE public.vendas_pagamentos (
  id bigint NOT NULL DEFAULT nextval('vendas_pagamentos_id_seq'::regclass),
  venda_id bigint NOT NULL,
  forma text NOT NULL,
  valor numeric NOT NULL DEFAULT 0,
  observacao text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT vendas_pagamentos_pkey PRIMARY KEY (id),
  CONSTRAINT vendas_pagamentos_venda_id_fkey FOREIGN KEY (venda_id) REFERENCES public.vendas(id),
  CONSTRAINT fk_vendas_pagamentos_created_by FOREIGN KEY (created_by) REFERENCES auth.users(id)
);