-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.alertas_estoque_controle (
  id integer NOT NULL DEFAULT nextval('alertas_estoque_controle_id_seq'::regclass),
  produto_id uuid NOT NULL,
  loja_id integer NOT NULL,
  estado character varying NOT NULL CHECK (estado::text = ANY (ARRAY['baixo'::character varying, 'zerado'::character varying, 'normal'::character varying]::text[])),
  quantidade_atual integer NOT NULL,
  quantidade_minima integer NOT NULL,
  ultimo_alerta_em timestamp with time zone DEFAULT now(),
  criado_em timestamp with time zone DEFAULT now(),
  atualizado_em timestamp with time zone DEFAULT now(),
  CONSTRAINT alertas_estoque_controle_pkey PRIMARY KEY (id),
  CONSTRAINT alertas_estoque_controle_produto_id_fkey FOREIGN KEY (produto_id) REFERENCES public.produtos(id),
  CONSTRAINT alertas_estoque_controle_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES public.lojas(id)
);
CREATE TABLE public.aparelhos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  imei character varying UNIQUE,
  numero_serie character varying,
  cor character varying,
  estado character varying NOT NULL CHECK (estado::text = ANY (ARRAY['novo'::character varying, 'usado'::character varying, 'seminovo'::character varying, 'recondicionado'::character varying]::text[])),
  condicao character varying CHECK (condicao::text = ANY (ARRAY['perfeito'::character varying, 'bom'::character varying, 'regular'::character varying, 'ruim'::character varying]::text[])),
  acessorios text,
  observacoes text,
  valor_compra numeric,
  valor_venda numeric,
  loja_id integer NOT NULL,
  status character varying NOT NULL DEFAULT 'disponivel'::character varying CHECK (status::text = ANY (ARRAY['disponivel'::character varying, 'vendido'::character varying, 'reservado'::character varying, 'defeito'::character varying, 'transferido'::character varying]::text[])),
  data_entrada timestamp with time zone DEFAULT now(),
  data_venda timestamp with time zone,
  venda_id uuid,
  criado_por uuid,
  criado_em timestamp with time zone DEFAULT now(),
  atualizado_em timestamp with time zone DEFAULT now(),
  atualizado_por uuid,
  marca character varying,
  modelo character varying,
  armazenamento character varying,
  memoria_ram character varying,
  exibir_catalogo boolean DEFAULT false,
  destaque boolean DEFAULT false,
  promocao boolean DEFAULT false,
  novidade boolean DEFAULT false,
  ordem_catalogo integer DEFAULT 0,
  CONSTRAINT aparelhos_pkey PRIMARY KEY (id),
  CONSTRAINT aparelhos_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES public.lojas(id),
  CONSTRAINT aparelhos_venda_id_fkey FOREIGN KEY (venda_id) REFERENCES public.vendas(id),
  CONSTRAINT aparelhos_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES auth.users(id),
  CONSTRAINT aparelhos_atualizado_por_fkey FOREIGN KEY (atualizado_por) REFERENCES auth.users(id)
);
CREATE TABLE public.audit_logs_deletions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tabela_nome character varying NOT NULL,
  registro_id uuid,
  dados_apagados jsonb NOT NULL,
  apagado_por uuid,
  criado_em timestamp with time zone DEFAULT now(),
  motivo text,
  usuario_nome character varying,
  numero_venda integer,
  valor_total numeric,
  cliente_id uuid,
  cliente_nome character varying,
  CONSTRAINT audit_logs_deletions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.caixas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  loja_id integer NOT NULL,
  usuario_abertura uuid NOT NULL,
  usuario_fechamento uuid,
  data_abertura timestamp with time zone NOT NULL DEFAULT now(),
  data_fechamento timestamp with time zone,
  saldo_inicial numeric NOT NULL DEFAULT 0,
  saldo_final numeric,
  status character varying NOT NULL DEFAULT 'aberto'::character varying CHECK (status::text = ANY (ARRAY['aberto'::character varying, 'fechado'::character varying]::text[])),
  observacoes_abertura text,
  observacoes_fechamento text,
  criado_em timestamp with time zone DEFAULT now(),
  atualizado_em timestamp with time zone DEFAULT now(),
  CONSTRAINT caixas_pkey PRIMARY KEY (id),
  CONSTRAINT caixas_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES public.lojas(id),
  CONSTRAINT caixas_usuario_abertura_fkey FOREIGN KEY (usuario_abertura) REFERENCES public.usuarios(id),
  CONSTRAINT caixas_usuario_fechamento_fkey FOREIGN KEY (usuario_fechamento) REFERENCES public.usuarios(id)
);
CREATE TABLE public.clientes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nome character varying NOT NULL,
  doc character varying UNIQUE,
  data_nascimento date,
  telefone character varying,
  telefone_secundario character varying,
  email character varying,
  cep character varying,
  logradouro character varying,
  numero character varying,
  complemento character varying,
  bairro character varying,
  cidade character varying,
  estado character varying,
  observacoes text,
  ativo boolean DEFAULT true,
  id_loja integer,
  criado_em timestamp with time zone DEFAULT now(),
  atualizado_em timestamp with time zone DEFAULT now(),
  criado_por uuid,
  atualizado_por uuid,
  CONSTRAINT clientes_pkey PRIMARY KEY (id),
  CONSTRAINT clientes_id_loja_fkey FOREIGN KEY (id_loja) REFERENCES public.lojas(id)
);
CREATE TABLE public.configuracoes_usuario (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  usuario_id uuid NOT NULL UNIQUE,
  notificacoes_email boolean DEFAULT true,
  notificacoes_push boolean DEFAULT true,
  notificacoes_estoque boolean DEFAULT true,
  modo_escuro boolean DEFAULT false,
  tema character varying DEFAULT 'default'::character varying,
  idioma character varying DEFAULT 'pt-BR'::character varying,
  formato_data character varying DEFAULT 'DD/MM/YYYY'::character varying,
  autenticacao_2fa boolean DEFAULT false,
  sessao_ativa boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT configuracoes_usuario_pkey PRIMARY KEY (id)
);
CREATE TABLE public.creditos_cliente (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cliente_id uuid NOT NULL,
  venda_origem_id uuid,
  devolucao_id uuid,
  valor_total numeric NOT NULL CHECK (valor_total <> 0::numeric),
  valor_utilizado numeric DEFAULT 0 CHECK (valor_utilizado >= 0::numeric),
  saldo numeric NOT NULL CHECK (saldo >= 0::numeric),
  motivo text,
  gerado_por uuid NOT NULL,
  criado_em timestamp with time zone DEFAULT now(),
  tipo character varying DEFAULT 'adicao'::character varying CHECK (tipo::text = ANY (ARRAY['adicao'::character varying, 'retirada'::character varying]::text[])),
  ordem_servico_id uuid,
  CONSTRAINT creditos_cliente_pkey PRIMARY KEY (id),
  CONSTRAINT creditos_cliente_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id),
  CONSTRAINT creditos_cliente_gerado_por_fkey FOREIGN KEY (gerado_por) REFERENCES public.usuarios(id),
  CONSTRAINT creditos_cliente_venda_origem_id_fkey FOREIGN KEY (venda_origem_id) REFERENCES public.vendas(id),
  CONSTRAINT creditos_cliente_devolucao_id_fkey FOREIGN KEY (devolucao_id) REFERENCES public.devolucoes_venda(id),
  CONSTRAINT creditos_cliente_ordem_servico_id_fkey FOREIGN KEY (ordem_servico_id) REFERENCES public.ordem_servico(id)
);
CREATE TABLE public.debug_logs (
  id bigint NOT NULL DEFAULT nextval('debug_logs_id_seq'::regclass),
  criado_em timestamp with time zone DEFAULT now(),
  contexto text,
  mensagem text,
  dados jsonb,
  CONSTRAINT debug_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.delete_context (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  usuario_id uuid,
  criado_em timestamp with time zone DEFAULT now(),
  CONSTRAINT delete_context_pkey PRIMARY KEY (id)
);
CREATE TABLE public.descontos_venda (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  venda_id uuid NOT NULL,
  tipo character varying NOT NULL CHECK (tipo::text = ANY (ARRAY['valor'::character varying, 'percentual'::character varying]::text[])),
  valor numeric NOT NULL CHECK (valor > 0::numeric),
  motivo text NOT NULL,
  aplicado_por uuid NOT NULL,
  criado_em timestamp with time zone DEFAULT now(),
  CONSTRAINT descontos_venda_pkey PRIMARY KEY (id),
  CONSTRAINT descontos_venda_aplicado_por_fkey FOREIGN KEY (aplicado_por) REFERENCES public.usuarios(id),
  CONSTRAINT descontos_venda_venda_id_fkey FOREIGN KEY (venda_id) REFERENCES public.vendas(id)
);
CREATE TABLE public.devolucoes_venda (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  venda_id uuid NOT NULL,
  tipo character varying NOT NULL CHECK (tipo::text = ANY (ARRAY['com_credito'::character varying, 'sem_credito'::character varying]::text[])),
  motivo text NOT NULL,
  valor_total numeric NOT NULL,
  realizado_por uuid NOT NULL,
  criado_em timestamp with time zone DEFAULT now(),
  forma_pagamento character varying CHECK (forma_pagamento::text = ANY (ARRAY['dinheiro'::character varying, 'pix'::character varying, 'debito'::character varying, 'credito'::character varying, 'credito_loja'::character varying]::text[])),
  CONSTRAINT devolucoes_venda_pkey PRIMARY KEY (id),
  CONSTRAINT devolucoes_venda_realizado_por_fkey FOREIGN KEY (realizado_por) REFERENCES public.usuarios(id),
  CONSTRAINT devolucoes_venda_venda_id_fkey FOREIGN KEY (venda_id) REFERENCES public.vendas(id)
);
CREATE TABLE public.estoque_lojas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  id_produto uuid NOT NULL,
  id_loja integer NOT NULL,
  quantidade integer NOT NULL DEFAULT 0 CHECK (quantidade >= 0),
  atualizado_por uuid,
  atualizado_em timestamp with time zone DEFAULT now(),
  CONSTRAINT estoque_lojas_pkey PRIMARY KEY (id),
  CONSTRAINT estoque_lojas_id_loja_fkey FOREIGN KEY (id_loja) REFERENCES public.lojas(id),
  CONSTRAINT estoque_lojas_atualizado_por_fkey FOREIGN KEY (atualizado_por) REFERENCES auth.users(id),
  CONSTRAINT estoque_lojas_id_produto_fkey FOREIGN KEY (id_produto) REFERENCES public.produtos(id)
);
CREATE TABLE public.fornecedores (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nome character varying NOT NULL,
  cnpj character varying UNIQUE,
  telefone character varying,
  email character varying,
  endereco text,
  cidade character varying,
  estado character varying,
  cep character varying,
  contato_nome character varying,
  contato_telefone character varying,
  observacoes text,
  ativo boolean DEFAULT true,
  criado_em timestamp with time zone DEFAULT now(),
  atualizado_em timestamp with time zone DEFAULT now(),
  criado_por uuid,
  atualizado_por uuid,
  CONSTRAINT fornecedores_pkey PRIMARY KEY (id),
  CONSTRAINT fornecedores_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES auth.users(id),
  CONSTRAINT fornecedores_atualizado_por_fkey FOREIGN KEY (atualizado_por) REFERENCES auth.users(id)
);
CREATE TABLE public.fotos_aparelhos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  aparelho_id uuid NOT NULL,
  url text NOT NULL,
  nome_arquivo character varying NOT NULL,
  tamanho integer,
  ordem integer DEFAULT 0,
  is_principal boolean DEFAULT false,
  criado_por uuid,
  criado_em timestamp with time zone DEFAULT now(),
  CONSTRAINT fotos_aparelhos_pkey PRIMARY KEY (id),
  CONSTRAINT fotos_aparelhos_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES auth.users(id),
  CONSTRAINT fotos_aparelhos_aparelho_id_fkey FOREIGN KEY (aparelho_id) REFERENCES public.aparelhos(id)
);
CREATE TABLE public.fotos_perfil (
  id integer NOT NULL DEFAULT nextval('fotos_perfil_id_seq'::regclass),
  usuario_id uuid,
  url text NOT NULL,
  criado_em timestamp with time zone DEFAULT now(),
  CONSTRAINT fotos_perfil_pkey PRIMARY KEY (id)
);
CREATE TABLE public.fotos_produtos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  produto_id uuid,
  url text NOT NULL,
  nome_arquivo character varying NOT NULL,
  tamanho integer,
  ordem integer DEFAULT 0,
  is_principal boolean DEFAULT false,
  criado_por uuid,
  criado_em timestamp with time zone DEFAULT now(),
  CONSTRAINT fotos_produtos_pkey PRIMARY KEY (id),
  CONSTRAINT fotos_produtos_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES auth.users(id),
  CONSTRAINT fotos_produtos_produto_id_fkey FOREIGN KEY (produto_id) REFERENCES public.produtos(id)
);
CREATE TABLE public.fotos_rma (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  rma_id uuid NOT NULL,
  url text NOT NULL,
  nome_arquivo character varying NOT NULL,
  tamanho integer NOT NULL,
  criado_por uuid NOT NULL,
  criado_em timestamp with time zone DEFAULT now(),
  CONSTRAINT fotos_rma_pkey PRIMARY KEY (id),
  CONSTRAINT fotos_rma_rma_id_fkey FOREIGN KEY (rma_id) REFERENCES public.rmas(id),
  CONSTRAINT fotos_rma_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES auth.users(id)
);
CREATE TABLE public.historico_estoque (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  id_produto uuid NOT NULL,
  id_loja integer,
  usuario_id uuid,
  quantidade_anterior integer,
  quantidade_nova integer,
  quantidade_alterada integer,
  observacao text,
  criado_em timestamp with time zone DEFAULT now(),
  id_ordem_servico uuid,
  tipo_movimentacao character varying NOT NULL DEFAULT 'ajuste'::character varying,
  motivo text,
  observacoes text,
  quantidade integer,
  CONSTRAINT historico_estoque_pkey PRIMARY KEY (id),
  CONSTRAINT historico_estoque_id_loja_fkey FOREIGN KEY (id_loja) REFERENCES public.lojas(id),
  CONSTRAINT historico_estoque_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES auth.users(id),
  CONSTRAINT historico_estoque_id_produto_fkey FOREIGN KEY (id_produto) REFERENCES public.produtos(id),
  CONSTRAINT historico_estoque_id_ordem_servico_fkey FOREIGN KEY (id_ordem_servico) REFERENCES public.ordem_servico(id)
);
CREATE TABLE public.historico_fornecedores (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  fornecedor_id uuid,
  operacao character varying NOT NULL CHECK (operacao::text = ANY (ARRAY['INSERT'::character varying, 'UPDATE'::character varying, 'DELETE'::character varying]::text[])),
  dados_anteriores jsonb,
  dados_novos jsonb,
  usuario_id uuid,
  criado_em timestamp with time zone DEFAULT now(),
  CONSTRAINT historico_fornecedores_pkey PRIMARY KEY (id),
  CONSTRAINT historico_fornecedores_fornecedor_id_fkey FOREIGN KEY (fornecedor_id) REFERENCES public.fornecedores(id),
  CONSTRAINT historico_fornecedores_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES auth.users(id)
);
CREATE TABLE public.historico_lojas (
  id integer NOT NULL DEFAULT nextval('historico_lojas_id_seq'::regclass),
  loja_id integer NOT NULL,
  usuario_id uuid,
  operacao character varying NOT NULL,
  dados_antigos jsonb,
  dados_novos jsonb,
  campos_modificados ARRAY,
  criado_em timestamp with time zone DEFAULT now(),
  CONSTRAINT historico_lojas_pkey PRIMARY KEY (id),
  CONSTRAINT fk_loja FOREIGN KEY (loja_id) REFERENCES public.lojas(id),
  CONSTRAINT fk_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
);
CREATE TABLE public.historico_ordem_servico (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  id_ordem_servico uuid NOT NULL,
  tipo_evento character varying NOT NULL CHECK (tipo_evento::text = ANY (ARRAY['criacao'::character varying, 'mudanca_status'::character varying, 'adicao_peca'::character varying, 'remocao_peca'::character varying, 'atualizacao_valores'::character varying, 'observacao'::character varying, 'conclusao'::character varying, 'devolucao'::character varying, 'cancelamento'::character varying, 'lancamento_caixa'::character varying, 'atribuicao_tecnico'::character varying, 'laudo_atualizado'::character varying, 'peca_adicionada'::character varying, 'peca_atualizada'::character varying]::text[])),
  status_anterior character varying,
  status_novo character varying,
  descricao text NOT NULL,
  dados_anteriores jsonb,
  dados_novos jsonb,
  criado_em timestamp with time zone DEFAULT now(),
  criado_por uuid,
  criado_por_nome character varying,
  CONSTRAINT historico_ordem_servico_pkey PRIMARY KEY (id),
  CONSTRAINT historico_ordem_servico_id_ordem_servico_fkey FOREIGN KEY (id_ordem_servico) REFERENCES public.ordem_servico(id),
  CONSTRAINT historico_ordem_servico_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES auth.users(id)
);
CREATE TABLE public.historico_produtos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  produto_id uuid NOT NULL,
  campo character varying NOT NULL,
  valor_antigo text,
  valor_novo text,
  usuario_id uuid,
  data_alteracao timestamp with time zone DEFAULT now(),
  CONSTRAINT historico_produtos_pkey PRIMARY KEY (id),
  CONSTRAINT historico_produtos_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES auth.users(id),
  CONSTRAINT historico_produtos_produto_id_fkey FOREIGN KEY (produto_id) REFERENCES public.produtos(id)
);
CREATE TABLE public.historico_rma (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  rma_id uuid NOT NULL,
  tipo_acao character varying NOT NULL CHECK (tipo_acao::text = ANY (ARRAY['criacao'::character varying, 'mudanca_status'::character varying, 'atualizacao'::character varying, 'adicao_foto'::character varying, 'adicao_observacao'::character varying, 'movimentacao_estoque'::character varying]::text[])),
  descricao text NOT NULL,
  dados_anteriores jsonb,
  dados_novos jsonb,
  criado_por uuid NOT NULL,
  criado_em timestamp with time zone DEFAULT now(),
  CONSTRAINT historico_rma_pkey PRIMARY KEY (id),
  CONSTRAINT historico_rma_rma_id_fkey FOREIGN KEY (rma_id) REFERENCES public.rmas(id),
  CONSTRAINT historico_rma_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES auth.users(id)
);
CREATE TABLE public.historico_usuarios (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  usuario_id uuid NOT NULL,
  usuario_alterou_id uuid,
  campo_alterado character varying NOT NULL,
  valor_anterior text,
  valor_novo text,
  tipo_operacao character varying NOT NULL CHECK (tipo_operacao::text = ANY (ARRAY['INSERT'::character varying, 'UPDATE'::character varying, 'DELETE'::character varying]::text[])),
  data_alteracao timestamp with time zone DEFAULT now(),
  CONSTRAINT historico_usuarios_pkey PRIMARY KEY (id),
  CONSTRAINT historico_usuarios_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id),
  CONSTRAINT historico_usuarios_usuario_alterou_id_fkey FOREIGN KEY (usuario_alterou_id) REFERENCES public.usuarios(id)
);
CREATE TABLE public.historico_vendas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  venda_id uuid NOT NULL,
  tipo_acao character varying NOT NULL CHECK (tipo_acao::text = ANY (ARRAY['criacao'::character varying, 'adicao_item'::character varying, 'remocao_item'::character varying, 'pagamento'::character varying, 'edicao_pagamento'::character varying, 'desconto'::character varying, 'devolucao'::character varying, 'finalizacao'::character varying, 'cancelamento'::character varying, 'edicao'::character varying, 'exclusao'::character varying]::text[])),
  descricao text NOT NULL,
  usuario_id uuid,
  criado_em timestamp with time zone DEFAULT now(),
  CONSTRAINT historico_vendas_pkey PRIMARY KEY (id),
  CONSTRAINT historico_vendas_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id),
  CONSTRAINT historico_vendas_venda_id_fkey FOREIGN KEY (venda_id) REFERENCES public.vendas(id)
);
CREATE TABLE public.itens_devolucao (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  devolucao_id uuid NOT NULL,
  item_venda_id uuid NOT NULL,
  quantidade integer NOT NULL CHECK (quantidade > 0),
  motivo text,
  criado_em timestamp with time zone DEFAULT now(),
  CONSTRAINT itens_devolucao_pkey PRIMARY KEY (id),
  CONSTRAINT itens_devolucao_devolucao_id_fkey FOREIGN KEY (devolucao_id) REFERENCES public.devolucoes_venda(id),
  CONSTRAINT itens_devolucao_item_venda_id_fkey FOREIGN KEY (item_venda_id) REFERENCES public.itens_venda(id)
);
CREATE TABLE public.itens_venda (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  venda_id uuid NOT NULL,
  produto_id uuid NOT NULL,
  produto_nome character varying NOT NULL,
  produto_codigo character varying NOT NULL,
  quantidade integer NOT NULL CHECK (quantidade > 0),
  preco_unitario numeric NOT NULL,
  subtotal numeric NOT NULL,
  devolvido integer NOT NULL DEFAULT 0 CHECK (devolvido >= 0),
  criado_em timestamp with time zone DEFAULT now(),
  desconto_tipo character varying CHECK (desconto_tipo::text = ANY (ARRAY['valor'::character varying, 'porcentagem'::character varying]::text[])),
  desconto_valor numeric DEFAULT 0,
  valor_desconto numeric DEFAULT 0,
  CONSTRAINT itens_venda_pkey PRIMARY KEY (id),
  CONSTRAINT itens_venda_produto_id_fkey FOREIGN KEY (produto_id) REFERENCES public.produtos(id),
  CONSTRAINT itens_venda_venda_id_fkey FOREIGN KEY (venda_id) REFERENCES public.vendas(id)
);
CREATE TABLE public.lojas (
  id integer NOT NULL DEFAULT nextval('lojas_id_seq'::regclass),
  nome text NOT NULL,
  cnpj character varying UNIQUE,
  telefone text,
  email text,
  endereco text,
  cidade text,
  estado character varying,
  cep character varying,
  ativo boolean DEFAULT true,
  criado_em timestamp with time zone DEFAULT now(),
  atualizado_em timestamp with time zone DEFAULT now(),
  CONSTRAINT lojas_pkey PRIMARY KEY (id)
);
CREATE TABLE public.lojas_fotos (
  id integer NOT NULL DEFAULT nextval('lojas_fotos_id_seq'::regclass),
  loja_id integer NOT NULL,
  url text NOT NULL,
  legenda text,
  ordem integer DEFAULT 0,
  is_principal boolean DEFAULT false,
  criado_em timestamp with time zone DEFAULT now(),
  atualizado_em timestamp with time zone DEFAULT now(),
  CONSTRAINT lojas_fotos_pkey PRIMARY KEY (id),
  CONSTRAINT fk_loja FOREIGN KEY (loja_id) REFERENCES public.lojas(id)
);
CREATE TABLE public.metas_usuarios (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  usuario_id uuid NOT NULL,
  loja_id integer,
  meta_mensal_vendas numeric DEFAULT 10000,
  meta_mensal_os integer DEFAULT 0,
  dias_uteis_mes integer DEFAULT 26,
  ativo boolean DEFAULT true,
  criado_em timestamp with time zone DEFAULT now(),
  atualizado_em timestamp with time zone DEFAULT now(),
  criado_por uuid,
  atualizado_por uuid,
  CONSTRAINT metas_usuarios_pkey PRIMARY KEY (id),
  CONSTRAINT metas_usuarios_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id),
  CONSTRAINT metas_usuarios_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES public.lojas(id),
  CONSTRAINT metas_usuarios_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES public.usuarios(id),
  CONSTRAINT metas_usuarios_atualizado_por_fkey FOREIGN KEY (atualizado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.notificacoes (
  id integer NOT NULL DEFAULT nextval('notificacoes_id_seq'::regclass),
  tipo character varying NOT NULL CHECK (tipo::text = ANY (ARRAY['estoque_baixo'::character varying, 'estoque_zerado'::character varying, 'estoque_reposto'::character varying, 'sistema'::character varying, 'produto_inativo'::character varying]::text[])),
  titulo character varying NOT NULL,
  mensagem text NOT NULL,
  produto_id uuid,
  loja_id integer,
  dados_extras jsonb,
  criado_em timestamp with time zone DEFAULT now(),
  expira_em timestamp with time zone,
  CONSTRAINT notificacoes_pkey PRIMARY KEY (id),
  CONSTRAINT notificacoes_produto_id_fkey FOREIGN KEY (produto_id) REFERENCES public.produtos(id),
  CONSTRAINT notificacoes_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES public.lojas(id)
);
CREATE TABLE public.notificacoes_usuarios (
  id integer NOT NULL DEFAULT nextval('notificacoes_usuarios_id_seq'::regclass),
  notificacao_id integer NOT NULL,
  usuario_id uuid NOT NULL,
  lida boolean DEFAULT false,
  lida_em timestamp with time zone,
  criado_em timestamp with time zone DEFAULT now(),
  CONSTRAINT notificacoes_usuarios_pkey PRIMARY KEY (id),
  CONSTRAINT notificacoes_usuarios_notificacao_id_fkey FOREIGN KEY (notificacao_id) REFERENCES public.notificacoes(id),
  CONSTRAINT notificacoes_usuarios_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
);
CREATE TABLE public.ordem_servico (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  numero_os integer NOT NULL DEFAULT nextval('ordem_servico_numero_os_seq'::regclass) UNIQUE,
  cliente_nome character varying NOT NULL,
  cliente_telefone character varying,
  cliente_email character varying,
  cliente_cpf_cnpj character varying,
  cliente_endereco text,
  equipamento_tipo character varying NOT NULL,
  equipamento_marca character varying,
  equipamento_modelo character varying,
  equipamento_numero_serie character varying,
  equipamento_senha character varying,
  defeito_reclamado text NOT NULL,
  estado_equipamento text,
  acessorios_entregues text,
  diagnostico text,
  servico_realizado text,
  observacoes_tecnicas text,
  valor_orcamento numeric,
  valor_desconto numeric DEFAULT 0,
  valor_total numeric,
  valor_pago numeric DEFAULT 0,
  data_entrada timestamp with time zone NOT NULL DEFAULT now(),
  previsao_entrega timestamp with time zone,
  data_inicio_servico timestamp with time zone,
  data_conclusao timestamp with time zone,
  data_entrega_cliente timestamp with time zone,
  status character varying NOT NULL DEFAULT 'aguardando'::character varying CHECK (status::text = ANY (ARRAY['aguardando'::character varying, 'aprovado'::character varying, 'em_diagnostico'::character varying, 'em_andamento'::character varying, 'aguardando_peca'::character varying, 'concluido'::character varying, 'entregue'::character varying, 'devolvida'::character varying, 'cancelado'::character varying, 'garantia'::character varying]::text[])),
  prioridade character varying DEFAULT 'normal'::character varying,
  id_loja integer NOT NULL,
  tecnico_responsavel uuid,
  criado_em timestamp with time zone DEFAULT now(),
  atualizado_em timestamp with time zone DEFAULT now(),
  criado_por uuid,
  atualizado_por uuid,
  laudo_diagnostico text,
  laudo_causa text,
  laudo_procedimentos text,
  laudo_recomendacoes text,
  laudo_garantia_dias integer DEFAULT 90,
  laudo_condicao_final text,
  tipo_cliente character varying DEFAULT 'consumidor_final'::character varying,
  tipo_garantia character varying DEFAULT 'servico_geral'::character varying,
  permite_multiplos_aparelhos boolean DEFAULT false,
  total_geral_multiplos numeric,
  CONSTRAINT ordem_servico_pkey PRIMARY KEY (id),
  CONSTRAINT ordem_servico_id_loja_fkey FOREIGN KEY (id_loja) REFERENCES public.lojas(id)
);
CREATE TABLE public.ordem_servico_anexos (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  id_ordem_servico uuid NOT NULL,
  tipo character varying NOT NULL,
  descricao text,
  url_arquivo text NOT NULL,
  nome_arquivo character varying,
  tamanho_arquivo integer,
  criado_em timestamp with time zone DEFAULT now(),
  criado_por uuid,
  CONSTRAINT ordem_servico_anexos_pkey PRIMARY KEY (id),
  CONSTRAINT ordem_servico_anexos_id_ordem_servico_fkey FOREIGN KEY (id_ordem_servico) REFERENCES public.ordem_servico(id),
  CONSTRAINT ordem_servico_anexos_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES auth.users(id)
);
CREATE TABLE public.ordem_servico_aparelhos (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  id_ordem_servico uuid NOT NULL,
  id_loja integer NOT NULL,
  sequencia integer NOT NULL CHECK (sequencia > 0),
  equipamento_tipo character varying NOT NULL,
  equipamento_marca character varying,
  equipamento_modelo character varying,
  equipamento_numero_serie character varying,
  equipamento_imei character varying,
  equipamento_senha character varying,
  defeito_reclamado text NOT NULL,
  estado_equipamento text,
  acessorios_entregues text,
  diagnostico text,
  valor_orcamento numeric,
  valor_desconto numeric DEFAULT 0,
  valor_total numeric,
  valor_pago numeric DEFAULT 0,
  servico_realizado text,
  laudo_diagnostico text,
  laudo_causa text,
  laudo_procedimentos text,
  laudo_recomendacoes text,
  laudo_garantia_dias integer DEFAULT 90,
  laudo_condicao_final text,
  observacoes_tecnicas text,
  status character varying NOT NULL DEFAULT 'ativo'::character varying CHECK (status::text = ANY (ARRAY['ativo'::character varying::text, 'removido'::character varying::text])),
  criado_em timestamp with time zone NOT NULL DEFAULT now(),
  atualizado_em timestamp with time zone NOT NULL DEFAULT now(),
  criado_por uuid,
  atualizado_por uuid,
  CONSTRAINT ordem_servico_aparelhos_pkey PRIMARY KEY (id),
  CONSTRAINT ordem_servico_aparelhos_id_ordem_servico_fkey FOREIGN KEY (id_ordem_servico) REFERENCES public.ordem_servico(id)
);
CREATE TABLE public.ordem_servico_caixa (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  id_ordem_servico uuid NOT NULL,
  id_loja integer NOT NULL,
  valor_total numeric NOT NULL,
  valor_pecas numeric DEFAULT 0,
  valor_servico numeric DEFAULT 0,
  valor_desconto numeric DEFAULT 0,
  forma_pagamento character varying,
  parcelas integer DEFAULT 1,
  status_caixa character varying DEFAULT 'pendente'::character varying,
  data_confirmacao timestamp with time zone,
  observacoes text,
  criado_em timestamp with time zone DEFAULT now(),
  criado_por uuid,
  confirmado_por uuid,
  CONSTRAINT ordem_servico_caixa_pkey PRIMARY KEY (id),
  CONSTRAINT ordem_servico_caixa_id_ordem_servico_fkey FOREIGN KEY (id_ordem_servico) REFERENCES public.ordem_servico(id),
  CONSTRAINT ordem_servico_caixa_id_loja_fkey FOREIGN KEY (id_loja) REFERENCES public.lojas(id),
  CONSTRAINT ordem_servico_caixa_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES auth.users(id),
  CONSTRAINT ordem_servico_caixa_confirmado_por_fkey FOREIGN KEY (confirmado_por) REFERENCES auth.users(id)
);
CREATE TABLE public.ordem_servico_fotos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  id_ordem_servico uuid NOT NULL,
  url text NOT NULL,
  ordem integer DEFAULT 0,
  is_principal boolean DEFAULT false,
  criado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  atualizado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ordem_servico_fotos_pkey PRIMARY KEY (id),
  CONSTRAINT ordem_servico_fotos_id_ordem_servico_fkey FOREIGN KEY (id_ordem_servico) REFERENCES public.ordem_servico(id)
);
CREATE TABLE public.ordem_servico_pagamentos (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  id_ordem_servico uuid NOT NULL,
  data_pagamento date NOT NULL,
  valor numeric NOT NULL CHECK (valor > 0::numeric),
  forma_pagamento character varying NOT NULL CHECK (forma_pagamento::text = ANY (ARRAY['dinheiro'::character varying, 'cartao_credito'::character varying, 'cartao_debito'::character varying, 'pix'::character varying, 'transferencia'::character varying, 'cheque'::character varying, 'credito_cliente'::character varying]::text[])),
  observacao text,
  criado_em timestamp with time zone DEFAULT now(),
  criado_por uuid,
  CONSTRAINT ordem_servico_pagamentos_pkey PRIMARY KEY (id),
  CONSTRAINT ordem_servico_pagamentos_id_ordem_servico_fkey FOREIGN KEY (id_ordem_servico) REFERENCES public.ordem_servico(id),
  CONSTRAINT ordem_servico_pagamentos_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES auth.users(id)
);
CREATE TABLE public.ordem_servico_pecas (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  id_ordem_servico uuid NOT NULL,
  id_produto uuid,
  id_loja integer NOT NULL,
  tipo_produto character varying NOT NULL DEFAULT 'estoque'::character varying,
  descricao_peca character varying NOT NULL,
  quantidade integer NOT NULL CHECK (quantidade > 0),
  valor_custo numeric NOT NULL,
  valor_venda numeric NOT NULL,
  valor_total numeric NOT NULL,
  estoque_reservado boolean DEFAULT false,
  estoque_baixado boolean DEFAULT false,
  data_reserva_estoque timestamp with time zone,
  data_baixa_estoque timestamp with time zone,
  observacao text,
  criado_em timestamp with time zone DEFAULT now(),
  criado_por uuid,
  CONSTRAINT ordem_servico_pecas_pkey PRIMARY KEY (id),
  CONSTRAINT ordem_servico_pecas_id_ordem_servico_fkey FOREIGN KEY (id_ordem_servico) REFERENCES public.ordem_servico(id),
  CONSTRAINT ordem_servico_pecas_id_produto_fkey FOREIGN KEY (id_produto) REFERENCES public.produtos(id),
  CONSTRAINT ordem_servico_pecas_id_loja_fkey FOREIGN KEY (id_loja) REFERENCES public.lojas(id),
  CONSTRAINT ordem_servico_pecas_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES auth.users(id)
);
CREATE TABLE public.pagamentos_venda (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  venda_id uuid NOT NULL,
  tipo_pagamento character varying NOT NULL CHECK (tipo_pagamento::text = ANY (ARRAY['dinheiro'::character varying, 'pix'::character varying, 'cartao_credito'::character varying, 'cartao_debito'::character varying, 'transferencia'::character varying, 'boleto'::character varying, 'credito_cliente'::character varying]::text[])),
  valor numeric NOT NULL CHECK (valor > 0::numeric),
  data_pagamento date NOT NULL,
  editado boolean DEFAULT false,
  editado_em timestamp with time zone,
  editado_por uuid,
  criado_em timestamp with time zone DEFAULT now(),
  criado_por uuid,
  CONSTRAINT pagamentos_venda_pkey PRIMARY KEY (id),
  CONSTRAINT pagamentos_venda_editado_por_fkey FOREIGN KEY (editado_por) REFERENCES public.usuarios(id),
  CONSTRAINT pagamentos_venda_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES public.usuarios(id),
  CONSTRAINT pagamentos_venda_venda_id_fkey FOREIGN KEY (venda_id) REFERENCES public.vendas(id)
);
CREATE TABLE public.permissoes (
  id integer NOT NULL DEFAULT nextval('permissoes_id_seq'::regclass),
  usuario_id uuid UNIQUE,
  permissoes jsonb NOT NULL DEFAULT '{}'::jsonb,
  criado_em timestamp with time zone DEFAULT now(),
  atualizado_em timestamp with time zone DEFAULT now(),
  loja_id integer,
  todas_lojas boolean DEFAULT false,
  CONSTRAINT permissoes_pkey PRIMARY KEY (id),
  CONSTRAINT permissoes_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id),
  CONSTRAINT permissoes_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES public.lojas(id)
);
CREATE TABLE public.produtos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  descricao text NOT NULL,
  modelos character varying,
  marca character varying,
  preco_compra numeric,
  preco_venda numeric,
  quantidade_minima integer DEFAULT 0,
  ativo boolean DEFAULT true,
  criado_por uuid,
  criado_em timestamp with time zone DEFAULT now(),
  atualizado_em timestamp with time zone DEFAULT now(),
  atualizado_por uuid,
  grupo character varying,
  categoria character varying,
  codigo_fabricante character varying,
  exibir_catalogo boolean DEFAULT false,
  destaque boolean DEFAULT false,
  promocao boolean DEFAULT false,
  novidade boolean DEFAULT false,
  ordem_catalogo integer DEFAULT 0,
  CONSTRAINT produtos_pkey PRIMARY KEY (id),
  CONSTRAINT produtos_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES auth.users(id),
  CONSTRAINT produtos_atualizado_por_fkey FOREIGN KEY (atualizado_por) REFERENCES auth.users(id)
);
CREATE TABLE public.produtos_fornecedores (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  produto_id uuid NOT NULL,
  fornecedor_id uuid NOT NULL,
  preco_custo numeric,
  prazo_entrega_dias integer,
  observacoes text,
  ativo boolean DEFAULT true,
  criado_em timestamp with time zone DEFAULT now(),
  atualizado_em timestamp with time zone DEFAULT now(),
  criado_por uuid,
  atualizado_por uuid,
  CONSTRAINT produtos_fornecedores_pkey PRIMARY KEY (id),
  CONSTRAINT produtos_fornecedores_produto_id_fkey FOREIGN KEY (produto_id) REFERENCES public.produtos(id),
  CONSTRAINT produtos_fornecedores_fornecedor_id_fkey FOREIGN KEY (fornecedor_id) REFERENCES public.fornecedores(id),
  CONSTRAINT produtos_fornecedores_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES auth.users(id),
  CONSTRAINT produtos_fornecedores_atualizado_por_fkey FOREIGN KEY (atualizado_por) REFERENCES auth.users(id)
);
CREATE TABLE public.quebra_pecas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  id_ordem_servico uuid,
  id_produto uuid,
  id_loja integer,
  quantidade integer NOT NULL CHECK (quantidade > 0),
  tipo_ocorrencia character varying NOT NULL DEFAULT 'quebra'::character varying,
  motivo text NOT NULL,
  responsavel character varying,
  valor_unitario numeric,
  valor_total numeric DEFAULT ((quantidade)::numeric * valor_unitario),
  descontar_tecnico boolean DEFAULT false,
  valor_descontado numeric DEFAULT 0,
  observacao_compensacao text,
  criado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  criado_por uuid,
  aprovado boolean DEFAULT false,
  aprovado_em timestamp with time zone,
  aprovado_por uuid,
  observacao_aprovacao text,
  produto_descricao text,
  CONSTRAINT quebra_pecas_pkey PRIMARY KEY (id),
  CONSTRAINT quebra_pecas_id_ordem_servico_fkey FOREIGN KEY (id_ordem_servico) REFERENCES public.ordem_servico(id),
  CONSTRAINT quebra_pecas_id_produto_fkey FOREIGN KEY (id_produto) REFERENCES public.produtos(id),
  CONSTRAINT quebra_pecas_id_loja_fkey FOREIGN KEY (id_loja) REFERENCES public.lojas(id),
  CONSTRAINT quebra_pecas_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES auth.users(id),
  CONSTRAINT quebra_pecas_aprovado_por_fkey FOREIGN KEY (aprovado_por) REFERENCES auth.users(id)
);
CREATE TABLE public.rmas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  numero_rma character varying NOT NULL UNIQUE,
  tipo_origem character varying NOT NULL CHECK (tipo_origem::text = ANY (ARRAY['interno_fornecedor'::character varying, 'cliente'::character varying]::text[])),
  tipo_rma character varying NOT NULL CHECK (tipo_rma::text = ANY (ARRAY['defeito_fabrica'::character varying, 'dano_transporte'::character varying, 'produto_errado'::character varying, 'nao_funciona'::character varying, 'arrependimento'::character varying, 'garantia'::character varying, 'outro'::character varying]::text[])),
  status character varying NOT NULL DEFAULT 'pendente'::character varying CHECK (status::text = ANY (ARRAY['pendente'::character varying, 'em_analise'::character varying, 'aprovado'::character varying, 'reprovado'::character varying, 'em_transito'::character varying, 'recebido'::character varying, 'concluido'::character varying, 'cancelado'::character varying]::text[])),
  produto_id uuid NOT NULL,
  loja_id integer NOT NULL,
  cliente_id uuid,
  fornecedor_id uuid,
  criado_por uuid NOT NULL,
  quantidade integer NOT NULL CHECK (quantidade > 0),
  motivo text NOT NULL,
  observacoes_assistencia text,
  criado_em timestamp with time zone DEFAULT now(),
  atualizado_em timestamp with time zone DEFAULT now(),
  CONSTRAINT rmas_pkey PRIMARY KEY (id),
  CONSTRAINT rmas_produto_id_fkey FOREIGN KEY (produto_id) REFERENCES public.produtos(id),
  CONSTRAINT rmas_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES public.lojas(id),
  CONSTRAINT rmas_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id),
  CONSTRAINT rmas_fornecedor_id_fkey FOREIGN KEY (fornecedor_id) REFERENCES public.fornecedores(id),
  CONSTRAINT rmas_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES auth.users(id)
);
CREATE TABLE public.sangrias_caixa (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  caixa_id uuid NOT NULL,
  valor numeric NOT NULL CHECK (valor > 0::numeric),
  motivo text NOT NULL,
  realizado_por uuid NOT NULL,
  criado_em timestamp with time zone DEFAULT now(),
  venda_id uuid,
  CONSTRAINT sangrias_caixa_pkey PRIMARY KEY (id),
  CONSTRAINT sangrias_caixa_venda_id_fkey FOREIGN KEY (venda_id) REFERENCES public.vendas(id),
  CONSTRAINT sangrias_caixa_caixa_id_fkey FOREIGN KEY (caixa_id) REFERENCES public.caixas(id),
  CONSTRAINT sangrias_caixa_realizado_por_fkey FOREIGN KEY (realizado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.tecnicos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nome character varying NOT NULL,
  cpf character varying UNIQUE,
  rg character varying,
  data_nascimento date,
  telefone character varying NOT NULL,
  email character varying,
  especialidades ARRAY,
  registro_profissional character varying,
  data_admissao date,
  data_demissao date,
  cor_agenda character varying DEFAULT '#3b82f6'::character varying,
  ativo boolean DEFAULT true,
  usuario_id uuid UNIQUE,
  id_loja integer,
  criado_em timestamp with time zone DEFAULT now(),
  atualizado_em timestamp with time zone DEFAULT now(),
  criado_por uuid,
  atualizado_por uuid,
  CONSTRAINT tecnicos_pkey PRIMARY KEY (id),
  CONSTRAINT tecnicos_id_loja_fkey FOREIGN KEY (id_loja) REFERENCES public.lojas(id)
);
CREATE TABLE public.textos_garantia (
  id integer NOT NULL DEFAULT nextval('textos_garantia_id_seq'::regclass),
  tipo_servico character varying NOT NULL UNIQUE,
  dias_garantia integer NOT NULL DEFAULT 0,
  titulo text NOT NULL,
  clausulas jsonb NOT NULL,
  ativo boolean NOT NULL DEFAULT true,
  criado_em timestamp with time zone NOT NULL DEFAULT now(),
  atualizado_em timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT textos_garantia_pkey PRIMARY KEY (id)
);
CREATE TABLE public.transferencias (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  loja_origem_id integer NOT NULL,
  loja_destino_id integer NOT NULL,
  usuario_id uuid NOT NULL,
  status character varying NOT NULL DEFAULT 'pendente'::character varying CHECK (status::text = ANY (ARRAY['pendente'::character varying::text, 'confirmada'::character varying::text, 'cancelada'::character varying::text])),
  observacao text,
  criado_em timestamp with time zone DEFAULT now(),
  confirmado_em timestamp with time zone,
  confirmado_por uuid,
  cancelado_em timestamp with time zone,
  cancelado_por uuid,
  motivo_cancelamento text,
  CONSTRAINT transferencias_pkey PRIMARY KEY (id),
  CONSTRAINT transferencias_cancelado_por_fkey FOREIGN KEY (cancelado_por) REFERENCES public.usuarios(id),
  CONSTRAINT transferencias_loja_origem_id_fkey FOREIGN KEY (loja_origem_id) REFERENCES public.lojas(id),
  CONSTRAINT transferencias_loja_destino_id_fkey FOREIGN KEY (loja_destino_id) REFERENCES public.lojas(id),
  CONSTRAINT transferencias_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id),
  CONSTRAINT transferencias_confirmado_por_fkey FOREIGN KEY (confirmado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.transferencias_itens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  transferencia_id uuid NOT NULL,
  produto_id uuid NOT NULL,
  quantidade integer NOT NULL CHECK (quantidade > 0),
  criado_em timestamp with time zone DEFAULT now(),
  CONSTRAINT transferencias_itens_pkey PRIMARY KEY (id),
  CONSTRAINT transferencias_itens_transferencia_id_fkey FOREIGN KEY (transferencia_id) REFERENCES public.transferencias(id),
  CONSTRAINT transferencias_itens_produto_id_fkey FOREIGN KEY (produto_id) REFERENCES public.produtos(id)
);
CREATE TABLE public.trocas_produtos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  venda_id uuid NOT NULL,
  item_venda_id uuid NOT NULL,
  produto_antigo_id uuid NOT NULL,
  produto_antigo_nome text NOT NULL,
  produto_antigo_preco numeric NOT NULL,
  quantidade_trocada integer NOT NULL CHECK (quantidade_trocada > 0),
  produto_novo_id uuid NOT NULL,
  produto_novo_nome text NOT NULL,
  produto_novo_preco numeric NOT NULL,
  diferenca_valor numeric NOT NULL,
  loja_id integer NOT NULL,
  usuario_id uuid,
  observacao text,
  criado_em timestamp with time zone DEFAULT now(),
  tipo_reembolso character varying CHECK (tipo_reembolso IS NULL OR (tipo_reembolso::text = ANY (ARRAY['credito'::character varying, 'manual'::character varying]::text[]))),
  forma_pagamento_reembolso character varying CHECK (forma_pagamento_reembolso IS NULL OR (forma_pagamento_reembolso::text = ANY (ARRAY['dinheiro'::character varying, 'pix'::character varying, 'transferencia'::character varying, 'cartao_debito'::character varying, 'cartao_credito'::character varying]::text[]))),
  CONSTRAINT trocas_produtos_pkey PRIMARY KEY (id),
  CONSTRAINT trocas_produtos_item_venda_id_fkey FOREIGN KEY (item_venda_id) REFERENCES public.itens_venda(id),
  CONSTRAINT trocas_produtos_produto_antigo_id_fkey FOREIGN KEY (produto_antigo_id) REFERENCES public.produtos(id),
  CONSTRAINT trocas_produtos_produto_novo_id_fkey FOREIGN KEY (produto_novo_id) REFERENCES public.produtos(id),
  CONSTRAINT trocas_produtos_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES public.lojas(id),
  CONSTRAINT trocas_produtos_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id),
  CONSTRAINT trocas_produtos_venda_id_fkey FOREIGN KEY (venda_id) REFERENCES public.vendas(id)
);
CREATE TABLE public.usuarios (
  id uuid NOT NULL,
  nome text NOT NULL,
  email text NOT NULL UNIQUE,
  telefone text,
  cpf character varying,
  ativo boolean DEFAULT true,
  criado_em timestamp with time zone DEFAULT now(),
  atualizado_em timestamp with time zone DEFAULT now(),
  CONSTRAINT usuarios_pkey PRIMARY KEY (id),
  CONSTRAINT usuarios_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.vendas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cliente_id uuid NOT NULL,
  loja_id integer NOT NULL,
  vendedor_id uuid NOT NULL,
  status character varying NOT NULL CHECK (status::text = ANY (ARRAY['em_andamento'::character varying, 'concluida'::character varying, 'cancelada'::character varying, 'devolvida'::character varying]::text[])),
  tipo character varying NOT NULL CHECK (tipo::text = ANY (ARRAY['normal'::character varying, 'fiada'::character varying]::text[])),
  data_prevista_pagamento date,
  valor_total numeric NOT NULL DEFAULT 0,
  valor_pago numeric NOT NULL DEFAULT 0,
  valor_desconto numeric NOT NULL DEFAULT 0,
  saldo_devedor numeric NOT NULL DEFAULT 0,
  criado_em timestamp with time zone DEFAULT now(),
  finalizado_em timestamp with time zone,
  finalizado_por uuid,
  cancelado_em timestamp with time zone,
  cancelado_por uuid,
  motivo_cancelamento text,
  numero_venda integer,
  CONSTRAINT vendas_pkey PRIMARY KEY (id),
  CONSTRAINT vendas_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id),
  CONSTRAINT vendas_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES public.lojas(id),
  CONSTRAINT vendas_vendedor_id_fkey FOREIGN KEY (vendedor_id) REFERENCES public.usuarios(id),
  CONSTRAINT vendas_finalizado_por_fkey FOREIGN KEY (finalizado_por) REFERENCES public.usuarios(id),
  CONSTRAINT vendas_cancelado_por_fkey FOREIGN KEY (cancelado_por) REFERENCES public.usuarios(id)
);